"""Updated Match Timezone

Revision ID: 0a1f804eaefe
Revises: 6a80b7589421
Create Date: 2025-04-16 23:28:52.920643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1f804eaefe'
down_revision = '6a80b7589421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_fcm_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_fcm_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
