"""Updated message model to accomondate kind

Revision ID: 424e55ce9922
Revises: ecc01fed586b
Create Date: 2025-04-22 02:22:14.926230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424e55ce9922'
down_revision = 'ecc01fed586b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
