"""Init DB

Revision ID: 6a80b7589421
Revises: 
Create Date: 2025-04-16 21:51:10.975906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a80b7589421'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ActivityMetrics')
    op.drop_table('DatingPreferences')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_online', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('last_online')

    op.create_table('DatingPreferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interested_in', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('age_preference_lower', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_preference_upper', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='DatingPreferences_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='DatingPreferences_pkey'),
    sa.UniqueConstraint('user_id', name='DatingPreferences_user_id_key')
    )
    op.create_table('ActivityMetrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('total_swipes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_matches', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_messages', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_reports', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ActivityMetrics_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ActivityMetrics_pkey')
    )
    # ### end Alembic commands ###
