"""Updated user model state_code to state

Revision ID: ecc01fed586b
Revises: 419da5109ef7
Create Date: 2025-04-21 21:28:48.445121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ecc01fed586b'
down_revision = '419da5109ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ActivityMetrics')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=10), nullable=True))
        batch_op.drop_column('state_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_column('state')

    op.create_table('ActivityMetrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('total_swipes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_matches', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_messages', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_reports', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ActivityMetrics_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ActivityMetrics_pkey')
    )
    # ### end Alembic commands ###
